<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62" started-at="2017-08-11T11:51:01Z" finished-at="2017-08-11T11:51:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62" started-at="2017-08-11T11:51:01Z" finished-at="2017-08-11T11:51:01Z">
      <class name="testscripts.scenario1.TC2">
        <test-method status="PASS" signature="suiteSetup(org.testng.ITestContext)[pri:0, instance:testscripts.scenario1.TC2@402f32ff]" name="suiteSetup" is-config="true" duration-ms="375" started-at="2017-08-11T17:21:01Z" finished-at="2017-08-11T17:21:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6b927fb]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetup -->
        <test-method status="FAIL" signature="runTC2()[pri:0, instance:testscripts.scenario1.TC2@402f32ff]" name="runTC2" duration-ms="31" started-at="2017-08-11T17:21:01Z" finished-at="2017-08-11T17:21:01Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.cognizant.framework.ExcelDataAccess.getRowCount(ExcelDataAccess.java:263)
	at supportlibraries.DriverScript.initializeTestIterations(DriverScript.java:146)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:91)
	at testscripts.scenario1.TC2.runTC2(TC2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTC2 -->
        <test-method status="PASS" signature="testMethodSetup()[pri:0, instance:testscripts.scenario1.TC2@402f32ff]" name="testMethodSetup" is-config="true" duration-ms="0" started-at="2017-08-11T17:21:01Z" finished-at="2017-08-11T17:21:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodSetup -->
        <test-method status="FAIL" signature="testMethodTearDown()[pri:0, instance:testscripts.scenario1.TC2@402f32ff]" name="testMethodTearDown" is-config="true" duration-ms="0" started-at="2017-08-11T17:21:01Z" finished-at="2017-08-11T17:21:01Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.cognizant.framework.Report.updateResultSummary(Report.java:340)
	at supportlibraries.TestCase.testMethodTearDown(TestCase.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodTearDown -->
        <test-method status="SKIP" signature="suiteTearDown()[pri:0, instance:testscripts.scenario1.TC2@402f32ff]" name="suiteTearDown" is-config="true" duration-ms="0" started-at="2017-08-11T17:21:01Z" finished-at="2017-08-11T17:21:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteTearDown -->
      </class> <!-- testscripts.scenario1.TC2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
