<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT012489" name="testscripts.scenario1.TC3" tests="1" failures="0" timestamp="3 May 2013 08:40:32 GMT" time="34.394" errors="1">
  <testcase name="runTC3" time="34.394" classname="testscripts.scenario1.TC3">
    <error type="java.lang.AssertionError" message="Login failed for valid user">
      <![CDATA[java.lang.AssertionError: Login failed for valid user
	at org.testng.Assert.fail(Assert.java:94)
	at supportlibraries.DriverScript.wrapUp(DriverScript.java:549)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:100)
	at testscripts.scenario1.TC3.runTC3(TC3.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- runTC3 -->
</testsuite> <!-- testscripts.scenario1.TC3 -->
